### ISSUE TITLE
Plugin/Theme name: Smash Balloon Custom Facebook Feed

### ISSUE THREAD

**Issue by risager** [khromov/clarity#10]
**Which plugin is this concerning?** - Please include a link to the listing page on WordPress.org
https://wordpress.org/plugins/custom-facebook-feed/

**Upload a screenshot from your WordPress admin where the nag is clearly visible**
<img width="600" alt="Screenshot 2022-03-08 at 10 43 47" src="https://user-images.githubusercontent.com/975590/157210820-acd447ff-fcd7-4351-af4b-7257b6fe0c9c.png">
<img width="400" alt="Screenshot 2022-03-08 at 10 39 18" src="https://user-images.githubusercontent.com/975590/157210867-b550345d-853f-4ab3-94db-e4031e2a812c.png">

**When does the nag appear?**
- [X ] Right away after installing the plugin
- [ ] After some time - 24hrs, 7 days, etc.
- [ ] Other: (Please specify)

**Do you have a proposed CSS rule that could hide this nag?**
.cff_notice.cff_review_notice_step_1
.cff_get_pro_highlight
.cff-notice-alert

* THANK YOU SO MUCH!

**Comment by khromov** [comment]
Will be in the next version!
