### ISSUE TITLE
Plugin/Theme name: 

### ISSUE THREAD

**Issue by tricarte** [khromov/clarity#11]
**Which plugin is this concerning?**
https://wordpress.org/plugins/duplicate-post/

**Upload a screenshot from your WordPress admin where the nag is clearly visible**
![Screenshot_20220309_115700](https://user-images.githubusercontent.com/3023026/157407570-d4166ef0-8de6-4a08-9981-e0932a55558c.png)

**When does the nag appear?**
- [ ] Right away after installing the plugin

**Do you have a proposed CSS rule that could hide this nag?**
#duplicate-post-notice

**Comment by khromov** [comment]
This was discussed and fixed (partially) in https://github.com/khromov/clarity/issues/8 but we can't remove the whole box for reasons explained in the other issue.
