### ISSUE TITLE
Admin Columns

### ISSUE THREAD

**Issue by senatorbright** [khromov/clarity#12]
**Which plugin is this concerning?** - Please include a link to the listing page on WordPress.org
[e.g https://wordpress.org/plugins/wordpress-seo/]
https://wordpress.org/plugins/codepress-admin-columns/

**Upload a screenshot from your WordPress admin where the nag is clearly visible**
(Drag an image here to upload it)
![image](https://user-images.githubusercontent.com/74133199/165030090-613d838f-5409-4a75-8ddc-c94a8450f465.png)

**When does the nag appear?**
- [ ] Right away after installing the plugin
- [ ] After some time - 24hrs, 7 days, etc.
- [ ] Other: (Please specify)
Article + wheel parameter for column

**Do you have a proposed CSS rule that could hide this nag?**
[e.g `#ws_sidebar_pro_ad`]

*(You can usually find the associated CSS by right-clicking the notification bar in your browser and selecting "Inspect element".)

**Comment by khromov** [comment]
Will be in the next version!
