### ISSUE TITLE
Plugin/Theme name: 

### ISSUE THREAD

**Issue by NetJon** [khromov/clarity#15]
**Which plugin is this concerning?** - Please include a link to the listing page on WordPress.org
[e.g https://wordpress.org/plugins/wordpress-seo/]

https://wordpress.org/plugins/elementskit-lite/

**Upload a screenshot from your WordPress admin where the nag is clearly visible**
(Drag an image here to upload it)
![wpmet-spam](https://user-images.githubusercontent.com/10630131/172791971-ddfbcc50-35e9-43eb-a5bf-24046efbc7d8.png)

**When does the nag appear?**
- [ ] Right away after installing the plugin
- [ ] After some time - 24hrs, 7 days, etc.
- [ ] Other: (Please specify)

I do not know when it appears for a new user.  This has been on my site for years, but the ad showed up recently.

**Do you have a proposed CSS rule that could hide this nag?**
[e.g `#ws_sidebar_pro_ad`]

It is an image link:  https://api.wpmet.com/auth/wp-content/uploads/2022/05/InPlugin-Banner-1.gif 

*(You can usually find the associated CSS by right-clicking the notification bar in your browser and selecting "Inspect element".)

**Comment by khromov** [comment]
Banner seems to have disappeared since this issue was filed, but there were some other intrusive banners in this plugin that were removed. Thanks!
