### ISSUE TITLE
Plugin/Theme name: 

### ISSUE THREAD

**Issue by Blackhawke** [khromov/clarity#21]
**Which plugin is this concerning?** - Please include a link to the listing page on WordPress.org
https://www.exactmetrics.com/ (They do not have a page on wordpress.org that I could find.)

**Upload a screenshot from your WordPress admin where the nag is clearly visible**
![Screenshot](https://user-images.githubusercontent.com/1757829/186965140-b9cce615-5790-444f-9122-081ceb0b36c8.png)

**When does the nag appear?**
- [ ] Right away after installing the plugin
- [ ] After some time - 24hrs, 7 days, etc.
- [ X] Other: (Please specify)

These "informative messages" (advertisements) appear on the Dashboard as soon as you login. They are _constant_ with this plugin (there were over 20 in 5 days! And each must be _manually_ dismissed) -- and there are so many they sometimes cover up the entire right side of the screen.

**Do you have a proposed CSS rule that could hide this nag?**
[e.g `#ws_sidebar_pro_ad`]

Here is the CSS rule that covers these popups.

.exactmetrics-tracking-notice p {

    font-size: 12px;
    color: #7f7f7f;
    font-weight: 400;
    margin: 0;
    padding: 0;
    line-height: 1.2;
    border: none;

}

**Comment by khromov** [comment]
Unfortunately these notifications does not seem possible to hide as there is a mix of informational and ad-related notification. Ask the developers to support the `CLARITY_AD_BLOCKER_ENABLED` constant under "For plugin and theme developers" on https://wp-clarity.dev/
