### ISSUE TITLE
ALD – Aliexpress Dropshipping and Fulfillment for WooCommerce

### ISSUE THREAD

**Issue by Lafimov** [khromov/clarity#22]
**Which plugin is this concerning?** - Please include a link to the listing page on WordPress.org
[e.g https://wordpress.org/plugins/wordpress-seo/]

**Upload a screenshot from your WordPress admin where the nag is clearly visible**
(Drag an image here to upload it)

**When does the nag appear?**
- [ ] Right away after installing the plugin
- [ ] After some time - 24hrs, 7 days, etc.

**Do you have a proposed CSS rule that could hide this nag?**
[e.g `#ws_sidebar_pro_ad`]

*(You can usually find the associated CSS by right-clicking the notification bar in your browser and selecting "Inspect element".)
![ALD](https://user-images.githubusercontent.com/112693272/188108210-5ac14f56-e99a-443f-ba34-e4aac8ccb149.jpg)

**Comment by Lafimov** [comment]
Please - delete ADS!

**Comment by khromov** [comment]
My suggestion for the future is to not install or support plugins that do this when you activate them. 🤷 

![Uploading 2022-09-13 21_52_29-Update Plugins ‹ Test — WordPress — Mozilla Firefox.png…]()
