### ISSUE TITLE
Erident Custom Login and Dashboard

### ISSUE THREAD

**Issue by kshyamasagarminz** [khromov/clarity#24]
**Which plugin is this concerning?** - Please include a link to the listing page on WordPress.org
[e.g https://wordpress.org/plugins/wordpress-seo/]

**Upload a screenshot from your WordPress admin where the nag is clearly visible**
(Drag an image here to upload it)

**When does the nag appear?**
- [ ] Right away after installing the plugin
- [ ] After some time - 24hrs, 7 days, etc.
- [ ] Other: (Please specify)

**Do you have a proposed CSS rule that could hide this nag?**
[e.g `#ws_sidebar_pro_ad`]

*(You can usually find the associated CSS by right-clicking the notification bar in your browser and selecting "Inspect element".)

**Comment by khromov** [comment]
Not enough info.
