### ISSUE TITLE
Members – Membership & User Role Editor Plugin

### ISSUE THREAD

**Issue by marties** [khromov/clarity#3]
https://fr.wordpress.org/plugins/members/

![Screenshot 2022-02-21 at 15-29-35 Tableau de bord ‹ Gervanne-Sye — WordPress](https://user-images.githubusercontent.com/1502538/154974668-efe7d565-5f3e-468b-a5a1-0c392bafb361.png)

**When does the nag appear?**
All the time in admin pages

**Do you have a proposed CSS rule that could hide this nag?**
.members-review-notice.is-dismissible.notice-info.notice

**Comment by jakob-metro** [comment]
I second this, was just going to submit the same request
