### ISSUE TITLE
Yoast SEO

### ISSUE THREAD

**Issue by marties** [khromov/clarity#4]
[**Which plugin is this concerning?** - Please include a link to the listing page on WordPress.org

https://fr.wordpress.org/plugins/wordpress-seo/

**Upload a screenshot from your WordPress admin where the nag is clearly visible**

![Screenshot 2022-02-21 at 15-59-43 Pages ‹ Gervanne-Sye — WordPress](https://user-images.githubusercontent.com/1502538/154980245-9710b29e-6eed-4c42-bf42-d2ec5221ab85.png)

**When does the nag appear?**
- [ ] After some time - 24hrs, 7 days, etc.

**Do you have a proposed CSS rule that could hide this nag?**
.is-dismissible.notice-warning.notice.yoast-notification

**Comment by khromov** [comment]
👋  Two small issues with this suggestion:

1. It is partly an informational message (it's triggered when you delete a post)
2. It doesn't have any classes that can easily be added without also breaking other notifications. (the suggested class is too generic)

Unfortunately it won't be possible to add as-is but I'm open for suggestions.

**Comment by khromov** [comment]
Closing due to lack of interest.
