### ISSUE TITLE
Plugin/Theme name: WooCommerce Direct Checkout plugin & Direct Checkout plugin

### ISSUE THREAD

**Issue by macford** [khromov/clarity#41]
https://quadlayers.com/portfolio/woocommerce-direct-checkout/?utm_source=aco_admin
https://quadlayers.com/portfolio/woocommerce-direct-checkout/?utm_source=wooccm_admin
Both ads are on wp-admin for my site
![screenshot-courses mypoa org-2023 02 23-08_09_44](https://user-images.githubusercontent.com/47402402/220964488-90f55a0f-de85-4c5d-97eb-f0ab682ef7bb.png)

Always shows in wp admin Dashboard. Closing the ad does not make it stay away.

**Which plugin is this concerning?** - Please include a link to the listing page on WordPress.org
[e.g https://wordpress.org/plugins/wordpress-seo/]
![screenshot-courses mypoa org-2023 02 23-08_09_44](https://user-images.githubusercontent.com/47402402/220964488-90f55a0f-de85-4c5d-97eb-f0ab682ef7bb.png)

**Upload a screenshot from your WordPress admin where the nag is clearly visible**
(Drag an image here to upload it)

**When does the nag appear?**
- [ ] Right away after installing the plugin
- [ ] After some time - 24hrs, 7 days, etc.
- [ ] Other: (Please specify)

**Do you have a proposed CSS rule that could hide this nag?**
[e.g `#ws_sidebar_pro_ad`]

*(You can usually find the associated CSS by right-clicking the notification bar in your browser and selecting "Inspect element".)

**Comment by khromov** [comment]
Fixed in #60
