### ISSUE TITLE
ManageWP or GoDaddy Pro dashboard

### ISSUE THREAD

**Issue by FranklinSeal** [khromov/clarity#44]
[ManageWP](https://managewp.com/) or [GoDaddy Pro](https://godaddy.com/pro) dashboard

![Screenshot 2023-05-10 at 2 14 24 PM](https://github.com/khromov/clarity/assets/116997394/4ee558c8-e720-43d7-9454-c2e978a481f4)

**Comment by FranklinSeal** [comment]
I installed your plugin thinking it would block it. It did not.

**Comment by khromov** [comment]
This is not an upsell as far as I can tell, it should go away once you connect the site.
