### ISSUE TITLE
CSS selector output doesn't seem to be working properly

### ISSUE THREAD

**Issue by jakob-metro** [khromov/clarity#5]
**Describe the bug**
I activated the plugin, and it didn't seem to be blocking _anything_. I did some sniffing and deduced that WP_Clarity->getDefinitions() doesn't seem to be doing what it's supposed to. If I debug line 61, it doesn't actually give me a list of selectors, it seems to return the whole contents of defenitions.txt

The expected output, would be a comma separated selector list appended by the `{ display: none!important }`. The actual output isn't a valid css selector, and thus doesn't block any popups.

```html
<style type="text/css">
      -- Yoast premium nags
.wpseo_content_wrapper #sidebar-container
.yoast_premium_upsell
#wpseo-local-seo-upsell
.yoast-settings-section-upsell

-- Better WordPress ReCAPTCHA
#bwp-get-social
.bwp-button-paypal
#bwp-sidebar-right

-- TJ Custom CSS
.tjcc-custom-css #postbox-container-1

-- CBX Custom Taxonomy Filter
.settings_page_wpcustomtaxfilterinadmin #postbox-container-1

-- Duplicate Posts
.settings_page_duplicatepost #wpbody-content .wrap > div

-- TODO: :above: look over

-- WPS Hide Login
div[id^="dnh-wrm"]

-- Ad Inserter
.notice-info.dst-notice

-- googleanalytics
#googleanalytics_terms_notice

-- Unyson
.fw-brz-dismiss

-- Elementor
div.elementor-message[data-notice_id="elementor_dev_promote"]

-- Redirection for Contact Form 7
.notice-success.wpcf7r-notice

-- Disable Comments
.dc-text__block.disable__comment__alert

-- Admin Menu Editor
#ws_sidebar_pro_ad

-- Premium Addons for Elementor
.pa-new-feature-notice

-- Redux
#redux-connect-message

-- Smush
.frash-notice-email

-- Easy Updates Manager
#easy-updates-manager-dashnotice

-- Metaslider
#metaslider-optin-notice
#extendifysdk_announcement
.updraft-ad-container

-- WP User Avatar "recommends" MailOption
.mo-admin-notice

-- post-smtp-donation
.post-smtp-donation

-- Widget Area Block
div[data-dismissible="notice-owa-sale-forever"]

-- Themeisle Companion
.neve-notice-upsell

-- Pagelayer Pro promo
#pagelayer_promo

-- Simple Custom Post Order rate nag
#simple-custom-post-order-epsilon-review-notice

-- Ultimate Social Media icons nags in various places
.sfsi_new_prmium_follw

-- The Events Calendar analytics nag
div.fs-slug-the-events-calendar[data-id="connect_account"]

-- WebP Converter for Media
div.notice[data-notice="webp-converter-for-media"]
.webpLoader__popup.webpPopup

-- Generic "Plugin Usage Tracker" class
.put-dismiss-notice

-- WP Mail SMTP
.wp-mail-smtp-review-notice
#wp-mail-smtp-pro-banner

-- Hopefully most Freemius ads
body div.promotion.fs-notice

-- Analytify
.analytify-review-thumbnail

-- Jetpack
.jitm-banner.is-upgrade-premium

-- Webcraftic Local Google Analytics
div[data-name*="wbcr_factory_notice_adverts"]

-- Forminator
.sui-subscription-notice
#sui-cross-sell-footer
.sui-cross-sell-modules {
        display: none !important;
      }
    </style>
```

**To Reproduce**
Activate the plugin and look at the style block in devtools

**Screenshots**
![image](https://user-images.githubusercontent.com/61976108/155015089-da823f6b-6600-42a2-9f19-215a405c0be9.png)  
![image](https://user-images.githubusercontent.com/61976108/155015192-e902f20f-7819-4d6a-8eba-1e430e4529ef.png)  

**Information**
 - WordPress version: 5.9
 - Clarity version: 1.2.220216
 - Currently active theme: Custom

**Comment by khromov** [comment]
Hey @jakob-metro !

I think I found the bug in the code that detects line endings. Are you perhaps running Windows? With version `1.3.220221` the issue should be fixed and as a bonus the block list selectors are now precompiled so it's much faster!

**Comment by jakob-metro** [comment]
I was indeed on Windows. That update did the trick, 
I ran the wp cli command as well and that generated a valid definitions.php file.

I assume that a new cache will be included in each update package, so I don't have to regenerate that manually right?

**Comment by khromov** [comment]
@jakob-metro Great to hear! Yup, the cached `definitions.php` file will be bundled with the plugin from now on, so you don't have to generate anything manually!
