### ISSUE TITLE
Menu Icons showing ad in Media Library

### ISSUE THREAD

**Issue by jonkratz** [khromov/clarity#51]
**Which plugin is this concerning?** - Menu Icons https://wordpress.org/plugins/menu-icons/

**Upload a screenshot from your WordPress admin where the nag is clearly visible**
<img width="1791" alt="Screenshot 2023-06-29 at 9 17 12 AM" src="https://github.com/khromov/clarity/assets/538172/ba1d2e4f-7f2c-4ae5-a7f0-ade1ba4eee94">

**When does the nag appear?**
- [ ] Only noticed much later. Could be right away, or delayed.

**Do you have a proposed CSS rule that could hide this nag?**
`#ti-optml-notice-helper {display: none;}` or perhaps `.media-modal #ti-optml-notice-helper {display: none;}`

**Comment by khromov** [comment]
Fixed in #60
