### ISSUE TITLE
Plugin/Theme name: 

### ISSUE THREAD

**Issue by JONZTA** [khromov/clarity#52]
**Which plugin is this concerning?** - Please include a link to the listing page on WordPress.org
https://catchthemes.com/themes/catch-bells/

**Upload a screenshot from your WordPress admin where the nag is clearly visible**
![image](https://github.com/khromov/clarity/assets/99376193/edb773b1-38bf-42b3-90e8-3dd4481b2180)

**When does the nag appear?**
- [x] Right away after installing the plugin
- [ ] After some time - 24hrs, 7 days, etc.
- [ ] Other: (Please specify)

**Do you have a proposed CSS rule that could hide this nag?**
not sure

*(You can usually find the associated CSS by right-clicking the notification bar in your browser and selecting "Inspect element".)

**Comment by khromov** [comment]
Fixed in #60
