### ISSUE TITLE
Plugin/Theme name: 

### ISSUE THREAD

**Issue by AZ-GIT-HUB** [khromov/clarity#53]
**Which plugin is this concerning?** - Please include a link to the listing page on WordPress.org
https://wordpress.org/plugins/wpdatatables/

**Upload a screenshot from your WordPress admin where the nag is clearly visible**
![image](https://github.com/khromov/clarity/assets/141672178/79a3d90d-5f3f-470b-b0b5-21278dba6dd2)

**When does the nag appear?**
- [XX ] Right away after installing the plugin
- [ ] After some time - 24hrs, 7 days, etc.
- [ ] Other: (Please specify)

**Do you have a proposed CSS rule that could hide this nag?**
NO

*(You can usually find the associated CSS by right-clicking the notification bar in your browser and selecting "Inspect element".)

**Comment by khromov** [comment]
Fixed in #60
