### ISSUE TITLE
VisualBusiness 

### ISSUE THREAD

**Issue by AZ-GIT-HUB** [khromov/clarity#54]
**Which plugin is this concerning?** - Please include a link to the listing page on WordPress.org
https://wordpress.org/themes/visualbusiness/

**Upload a screenshot from your WordPress admin where the nag is clearly visible**
![image](https://github.com/khromov/clarity/assets/141672178/db4327d0-28ea-4d69-8378-64300e63b994)

**When does the nag appear?**
- [XX ] Right away after installing the plugin
- [ ] After some time - 24hrs, 7 days, etc.
- [ ] Other: (Please specify)

**Do you have a proposed CSS rule that could hide this nag?**
NO - I could not hide it with CSS

*(You can usually find the associated CSS by right-clicking the notification bar in your browser and selecting "Inspect element".)

**Comment by khromov** [comment]
Fixed in #60
