### ISSUE TITLE
Plugin/Theme name: TagDiv Newspaper Wordpress Theme

### ISSUE THREAD

**Issue by volkancaliskan** [khromov/clarity#55]
**Which plugin is this concerning?** - Please include a link to the listing page on WordPress.org

https://themeforest.net/item/newspaper/5489609

**Upload a screenshot from your WordPress admin where the nag is clearly visible**

<img width="1931" alt="Screenshot 2023-09-10 at 20 24 05" src="https://github.com/khromov/clarity/assets/1011365/2b064a8f-b27e-4e98-99e3-180d50273c4d">

**When does the nag appear?**
- [x] Right away after installing the plugin (**Updated the theme**)
- [ ] After some time - 24hrs, 7 days, etc.
- [ ] Other: (Please specify)

**Do you have a proposed CSS rule that could hide this nag?**

`.td-admin-web-services`

<img width="695" alt="Screenshot 2023-09-10 at 20 29 41" src="https://github.com/khromov/clarity/assets/1011365/20287ab9-09b3-4e36-a11b-121855f9dc7d">

**Comment by khromov** [comment]
Fixed in #60
