### ISSUE TITLE
Plugin/Theme name: Multicollab

### ISSUE THREAD

**Issue by groenroos** [khromov/clarity#56]
**Which plugin is this concerning?** https://wordpress.org/plugins/commenting-feature/

**Upload a screenshot from your WordPress admin where the nag is clearly visible**

<img width="864" alt="Screenshot 2023-10-24 at 13 15 59" src="https://github.com/khromov/clarity/assets/951547/8b3f67fa-6414-4c55-a9a3-bf257b78ea98">

**When does the nag appear?**
- [x] Right away after installing the plugin
- [ ] After some time - 24hrs, 7 days, etc.
- [ ] Other: (Please specify)

**Do you have a proposed CSS rule that could hide this nag?**
`.cf-plugin-popup`

**Comment by khromov** [comment]
Fixed in #60
