### ISSUE TITLE
Plugin/Theme name: Menu Icons by ThemeIsle

### ISSUE THREAD

**Issue by chrslcy** [khromov/clarity#59]
**Which plugin is this concerning?** - Please include a link to the listing page on WordPress.org

https://wordpress.org/plugins/menu-icons/

**Upload a screenshot from your WordPress admin where the nag is clearly visible**

![2023-11-02_100006](https://github.com/khromov/clarity/assets/19710471/5dfd4703-c469-42cd-a712-6a472063ad1d)

**When does the nag appear?**

- [X] Right away after installing the plugin

**Do you have a proposed CSS rule that could hide this nag?**

.menu-icon-dashboard-notice

*(You can usually find the associated CSS by right-clicking the notification bar in your browser and selecting "Inspect element".)

**Comment by chrslcy** [comment]
Biggest issue with this plugin is that it displays the ad to Editors, which is the role I assign to clients.

**Comment by khromov** [comment]
Fixed in #60
