### ISSUE TITLE
WP GuppyPlugin/Theme name: 

### ISSUE THREAD

**Issue by proalex010** [khromov/clarity#6]
**Which plugin is this concerning?** - Please include a link to the listing page on WordPress.org
[e.g https://wordpress.org/plugins/wordpress-seo/]

**Upload a screenshot from your WordPress admin where the nag is clearly visible**
(Drag an image here to upload it)

**When does the nag appear?**
- [ ] Right away after installing the plugin
- [ ] After some time - 24hrs, 7 days, etc.
- [ ] Other: (Please specify)

**Do you have a proposed CSS rule that could hide this nag?**
[e.g `#ws_sidebar_pro_ad`]

*(You can usually find the associated CSS by right-clicking the notification bar in your browser and selecting "Inspect element".)

**Comment by khromov** [comment]
WP Guppy seems like a premium-only plugin, so it won't be able to be added unless someone can make a PR with a working selector and explain the upsells and when they appear.
