### ISSUE TITLE
Yoast Duplicate Post

### ISSUE THREAD

**Issue by jakob-metro** [khromov/clarity#8]
**Which plugin is this concerning?** - Please include a link to the listing page on WordPress.org
https://wordpress.org/plugins/duplicate-post/

**Upload a screenshot from your WordPress admin where the nag is clearly visible**
![image](https://user-images.githubusercontent.com/61976108/156017528-bfc40eba-f299-4fad-ab18-30fcd205b89a.png)

**When does the nag appear?**
- [ ] Right away after installing the plugin
- [ ] After some time - 24hrs, 7 days, etc.
- [x] Other: (I think it might appear when an update has been installed)

**Do you have a proposed CSS rule that could hide this nag?**
`#duplicate-post-notice`

Not sure what other notices might use the id #duplicate-post-notice, there isn't a class that's specific to this call to action.
![image](https://user-images.githubusercontent.com/61976108/156017698-de4b2413-f6e5-4d27-a611-518400755fcd.png)

**Comment by khromov** [comment]
@jakob-metro Unfortunately update notifications are a tough nut to crack. They're not included in the existing [acceptable ads policy](https://github.com/khromov/clarity/blob/master/acceptable-ads-policy.md) and they are in fact useful in many ways.

But the problem with this notification is that it asks you for your email address. So I removed just that part while keeping the rest of the message in place.
