### ISSUE TITLE
Plugin/Theme name: Smash Balloon Social Post Feed

### ISSUE THREAD

**Issue by risager** [khromov/clarity#9]
**Which plugin is this concerning?** - Please include a link to the listing page on WordPress.org
https://wordpress.org/plugins/custom-facebook-feed/

**Upload a screenshot from your WordPress admin where the nag is clearly visible**
<img width="600" alt="smashballoon" src="https://user-images.githubusercontent.com/975590/156875422-dd836de5-f01b-474d-ba05-a4fcb44b5f4f.png">

**When does the nag appear?**
- [ ] Right away after installing the plugin

**Do you have a proposed CSS rule that could hide this nag?**
.cff-settings-cta

**Comment by khromov** [comment]
Fixed in https://github.com/khromov/clarity/commit/8baff2ef624c7759dcc7b8b9ddb83191601a490a
